---
version: 2
updates:
  - package-ecosystem: "cargo"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "weekly"
