---
name: ci
permissions:
  contents: read

"on":
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  lint:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: r7kamura/rust-problem-matchers@v1
      - run: cargo fmt --all -- --check
      - uses: xt0rted/markdownlint-problem-matcher@v3
      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: |
            **/*.md
            #CODE_OF_CONDUCT.md
      - uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_file_or_dir: "."
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deny:
    strategy:
      matrix:
        check:
          - advisories
          - bans licenses sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: "1.87.0"
          command: check ${{ matrix.check }}

  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    # Prevent beta warnings from causing CI failure
    continue-on-error: ${{ matrix.rust == 'beta' }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - run: |
          cargo +${{ matrix.rust }} clippy \
            --all \
            --all-features

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
        features:
          - none
          - alloc
          - serde
          - serde,alloc
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: r7kamura/rust-problem-matchers@v1
      - run: |
          if [ ${{ matrix.features }} == "none" ]; then
            cargo +${{ matrix.rust }} build \
              --workspace \
              --release \
              --no-default-features
          else
            cargo +${{ matrix.rust }} build \
              --workspace \
              --release \
              --no-default-features \
              --features "${{ matrix.features }}"
          fi

  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    # Prevent beta warnings from causing CI failure
    continue-on-error: ${{ matrix.rust == 'beta' }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: r7kamura/rust-problem-matchers@v1
      - run: |
          cargo +${{ matrix.rust }} doc \
            --workspace \
            --release \
            --all-features \
            --no-deps

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-nextest
      - run: |
          cargo nextest run \
            --workspace \
            --profile ci
      - uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          files: target/nextest/ci/junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@cargo-nextest
      - name: Run tests with coverage
        run: |
          cargo llvm-cov nextest \
            --no-report \
            --workspace \
            --all-features \
            --profile ci \
            --hide-progress-bar
          cargo llvm-cov \
            --no-report \
            --workspace \
            --doc
          cargo llvm-cov report \
            --doctests \
            --lcov \
            --output-path lcov.info
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
